---
# WireGuard server configuration tasks

- name: Show WireGuard Interfaces
  ansible.builtin.shell:
    cmd: wg show
  register: wg_output

- debug:
  msg: wg_output.stdout_lines[0]

# - name: Generate WireGuard key pair
#   ansible.builtin.shell: 
#     cmd: wg genkey | tee privatekey | wg pubkey > {{ wireguard_directory }}/publickey
#     chdir: "{{ wireguard_directory }}"
#   register: command_output
#   failed_when: command_output.rc != 0
#   when: wg_output.stdout_lines[interface] != wg0

# - name: Generate server configuration
#   ansible.builtin.template:
#     src: wg0.conf.j2
#     dest: /etc/wireguard/wg0.conf
#     owner: root
#     group: root
#     mode: '0600'

# - name: Get server Private Key
#   ansible.builtin.command: cat {{ wireguard_directory }}/privatekey
#   register: private_key

# - name: Add server PrivateKey to config file
#   ansible.builtin.lineinfile:
#     path: /etc/wireguard/wg0.conf
#     regexp: "^PrivateKey"
#     line: "PrivateKey = {{ private_key.stdout }}"
