---
# WireGuard server configuration tasks

- name: Show WireGuard Interfaces
  ansible.builtin.shell:
    cmd: wg show
  register: wg_output

- ansible.builtin.debug: Debug WireGuard interface
    msg: "{{ wg_output }}"
  ignore_errors: true

- name: Generate WireGuard key pair
  ansible.builtin.shell:
    cmd: wg genkey | tee privatekey | wg pubkey > {{ wireguard_directory }}/publickey
    chdir: "{{ wireguard_directory }}"
  register: command_output
  failed_when: command_output.rc != 0
  when: wg_output.stdout == ""

- name: Generate server configuration
  ansible.builtin.template:
    src: wireguard.conf.j2
    dest: /etc/wireguard/"{{ wireguard_interface }}".conf
    owner: root
    group: root
    mode: '0600'

- name: Get server Private Key
  ansible.builtin.command: cat {{ wireguard_directory }}/privatekey
  register: private_key

- name: Add server PrivateKey to config file
  ansible.builtin.lineinfile:
    path: /etc/wireguard/"{{ wireguard_interface }}".conf
    regexp: "^PrivateKey"
    line: "PrivateKey = {{ private_key.stdout }}"
