---
# Install WireGuard server

- name: Install WireGuard package
  ansible.builtin.apt:
    update_cache: yes
    name: wireguard
    state: present

- name: Enable IP forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true

- name: Create "/etc/wireguard/keys" directory
  ansible.builtin.file:
    path: /etc/wireguard/keys
    state: directory
    owner: root
    group: root
    mode: 0700