---
# Start WireGuard service

- name: Starting WireGuard service
  ansible.builtin.shell:
    cmd: wg-quick down wg0 || wg-quick up wg0 && systemctl enable wg-quick@wg0.service

- name: Show WireGuard Interfaces
  ansible.builtin.shell:
    cmd: wg show