---
# Start WireGuard service

- name: Show WireGuard Interfaces
  ansible.builtin.shell:
    cmd: wg show
  register: wg_output

- debug:
    msg: "{{ wg_output }}"
  ignore_errors: True

# - name: Restart WireGuard service if adding peers
#   ansible.builtin.shell:
#     cmd: systemctl restart wg-quick@wg0.service
#   when: wg_output.stdout != ""

- name: Stoping WireGuard service
  ansible.builtin.shell:
    cmd: wg-quick down "{{ wireguard_interface }}"
  #when: ('wg0' in wg_output.stdout_lines[0])
  when: wg_output.stdout != ""

- name: Starting WireGuard service
  ansible.builtin.shell:
    cmd: wg-quick up "{{ wireguard_interface }}" && systemctl enable wg-quick@wg0.service
