---
# Start WireGuard service
# Si "wg show" sort un résultat, alors restart le service ou down + up
# Sinon juste start

- name: Show WireGuard Interfaces
  ansible.builtin.shell:
    cmd: wg show
  register: wg_output

- debug:
    msg: "{{ wg_output }}"

- name: Starting WireGuard service
  ansible.builtin.shell:
    cmd: wg-quick down wg0 || wg-quick up wg0 && systemctl enable wg-quick@wg0.service
  # when: wg_output

- name: Show WireGuard Interfaces
  ansible.builtin.shell:
    cmd: wg show